apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-deployments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/aadisrt1045/argocd-alerts.git
        revision: HEAD
        directories:
          - path: argocd-applicationset-apps/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/aadisrt1045/argocd-alerts.git
        targetRevision: HEAD
        path: argocd-applicationset-apps/helm-chart
        helm:
          valueFiles:
            - ../apps/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptio
