apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-deployments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/<your-org>/<your-repo>.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/<your-org>/<your-repo>.git
        targetRevision: HEAD
        path: helm-chart
        helm:
          valueFiles:
            - ../../apps/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

